theme: jekyll-theme-minimal
title: Support
logo: img/sunfounder-steam-education.png
logo_url: "https://www.sunfoudner.com"
show_download: true
description: "support from sunfounder"
enable_view: false