theme: jekyll-theme-minimal
title: SunFounder Support
SEOTitle: SunFounder Support
header-img: img/home-bg-hill.jpg
email: service@sunfounder.com
description: "support from sunfounder"
keyword: "sunfounder"
url: "https://SunFounderSupport.github.io"
baseurl: ""
